// vue3-mobile/src/components/Scroll/index.vue
<template>
  <div
    class="slider-wrapper"
    :ref="sliderWrapperElemRef"
    :style="{
      height:
        (typeof height === 'number' ? `${height}px` : height) || undefined,
    }"
  >
    <div class="slider" :ref="sliderRef">
      <div class="slider-group" :ref="sliderGroupRef">
        <slot name="children"></slot>
      </div>
      <div v-if="mode === 'list-detail'" class="pullup-tips">
        <div v-if="beforePullUp" class="before-trigger">
          <span class="pullup-txt">Pull up and load more</span>
        </div>
        <div v-else class="after-trigger">
          <span class="pullup-txt">Loading...</span>
        </div>
      </div>
    </div>
    <div v-if="mode === 'banner' && dots.length > 0" class="dots">
      <div
        v-for="(dot, index) in dots"
        :key="index"
        :class="['dots-item', currentPageIndex === index ? 'active' : '']"
      ></div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive, ref, shallowReactive } from "vue";
import Toast from "vant/es/toast";
import "vant/es/toast/style";
import BScroll from "@better-scroll/core";
import PullDown from "@better-scroll/pull-down";
import PullUp from "@better-scroll/pull-up";
import Slide from "@better-scroll/slide";

export default defineComponent({
  setup(props: any, {slots}) {
    
    // const {
    //   mode,
    //   config,
    //   children,
    //   height,
    //   width,
    //   click,
    //   pullDown,
    //   fetchDataForPullUp,
    // } = props;
    const scroll: any = slots.default
    
    let children = scroll()
    children = children[0].children
    // console.log(children);
    // debugger
    const instance = ref<any>({ excuting: false });
    const sliderRef = ref<any>({});
    const sliderGroupRef = ref<any>({});
    const sliderWrapperElemRef = ref<any>({});
    const currentPageIndex = ref<number>(0);
    const dots = ref<any[]>([])
    const beforePullUp = ref<boolean>(true);

    const initial = () => {
      if (children.length === 0) return;
      if (props.mode === "banner") BScroll.use(Slide);
      if (props.mode === "list-detail") {
        const use: any = BScroll.use;
        use(PullDown);
        use(PullUp);
      }
      instance.value = {
        ...instance.value,
        bscroll: new BScroll(sliderRef.value, props.config.bscroll),
      };
      const bscroll = instance.value.bscroll;
      const hooks = bscroll.scroller.actionsHandler.hooks;
      hooks.on("click", (event: any) => props.click && props.click());
      if (props.mode === "banner") {
        bscroll.on("slideWillChange", (page: any) => {
          currentPageIndex.value = page.pageX;
        });
      }

      // 问题: 没有进行事件解绑
      if (props.mode === "list-detail" && props.pullDown && props.fetchDataForPullUp) {
        bscroll.on("pullingDown", () => props.pullDown(bscroll));

        bscroll.on("pullingUp", async () => {
          beforePullUp.value = false;
          let res = await props.fetchDataForPullUp();
          if (!res.success) {
            Toast.fail({ message: res.msg });
            bscroll.finishPullUp();
          } else {
            bscroll.finishPullUp();
            bscroll.refresh();
          }
          beforePullUp.value = true;
        });
      }
    };


    const setSliderWidth = () => {
    let elRefSlider = sliderRef.value
    let elRefSliderGroup = sliderGroupRef.value
    let children = elRefSliderGroup.children
    let sliderWidth = elRefSlider.clientWidth

    const marginLeft = 10
    if (props.mode === "banner") {
      dots.value = Array.from({ length: 10 }).map((item) => true)
    }
    for (let i = 0, len = children.length; i < len; i++) {
      let child = children[i]
      child.props.class += "slider-item"
      if (props.mode === "normal-scroll-x") {
        // 添加margin-left: 5px, 用于隔开
        child.props.class += "margin"
        child.props.style.width = typeof props.width === "number" ? `${props.width}px` : props.width
      }
    }
    if (props.mode === "banner") {
      elRefSliderGroup.style.width = `${sliderWidth * children.length}px`
    } else if (props.mode === "normal-scroll-x") {
      const childClientWidth = children[0].children[0].clientWidth
      elRefSliderGroup.style.width = `${(childClientWidth + marginLeft) * children.length}px`
    }
  }

  const setSliderHeight = () => {
    sliderRef.value.style.height = sliderWrapperElemRef.value.clientHeight + "px"
  }


    return {
      sliderRef,
      sliderGroupRef,
      sliderWrapperElemRef,
      currentPageIndex,
    };
  },
});
</script>

<style lang="less">
@import "./index.less";
</style>

// react-mobile/src/components/Scroll/index.tsx
import { useState, useEffect, useRef } from "react"
import { connect } from "react-redux"
import { Toast } from "antd-mobile"

import BScroll from "@better-scroll/core"
import PullDown from "@better-scroll/pull-down"
import PullUp from "@better-scroll/pull-up"
import Slide from "@better-scroll/slide"
import "./index.less"

// normal-scroll-y 普通纵向滑动
// normal-scroll-x 普通横向滑动
// banner banner模式

const Slider = (props: any) => {
  const { mode, config, children, height, width, pullDown, fetchDataForPullUp, click } = props

  const instance = useRef<any>()
  const sliderRef = useRef<any>(null)
  const sliderGroupRef = useRef<any>(null)
  const sliderWrapperElemRef = useRef<any>()
  const [currentPageIndex, setCurrentPageIndex] = useState(0)
  const [dots, setDots] = useState<any[]>([])
  const [beforePullUp, setBeforePullUp] = useState<boolean>(true)

  const initial = () => {
    if (children.length === 0) return
    if (mode === "banner") BScroll.use(Slide)
    if (mode === "list-detail") {
      const use: any = BScroll.use
      use(PullDown)
      use(PullUp)
    }
    instance.current = { ...instance.current, bscroll: new BScroll(sliderRef.current, config.bscroll) }
    const bscroll = instance.current.bscroll
    const hooks = bscroll.scroller.actionsHandler.hooks
    hooks.on("click", (event: any) => click && click())
    if (mode === "banner") {
      bscroll.on("slideWillChange", (page: any) => {
        setCurrentPageIndex(page.pageX)
      })
    }

    // 问题: 没有进行事件解绑
    if (mode === "list-detail" && pullDown && fetchDataForPullUp) {
      bscroll.on("pullingDown", () => pullDown(bscroll))

      bscroll.on("pullingUp", async () => {
        setBeforePullUp(false)
        let res = await fetchDataForPullUp()
        if (!res.success) {
          Toast.fail(res.msg, 1.5, () => {}, false)
          bscroll.finishPullUp()
        } else {
          bscroll.finishPullUp()
          bscroll.refresh()
        }
        setBeforePullUp(true)
      })
    }
  }

  const setSliderWidth = () => {
    let elRefSlider = sliderRef.current
    let elRefSliderGroup = sliderGroupRef.current
    let children = elRefSliderGroup.children
    let sliderWidth = elRefSlider.clientWidth

    const marginLeft = 10
    if (mode === "banner") {
      setDots(Array.from({ length: 10 }).map((item) => true))
    }
    for (let i = 0, len = children.length; i < len; i++) {
      let child = children[i]
      child.classList.add("slider-item")
      if (mode === "normal-scroll-x") {
        // 添加margin-left: 5px, 用于隔开
        child.classList.add("margin")
        child.style.width = typeof width === "number" ? `${width}px` : width
      }
    }
    if (mode === "banner") {
      elRefSliderGroup.style.width = `${sliderWidth * children.length}px`
    } else if (mode === "normal-scroll-x") {
      const childClientWidth = children[0].children[0].clientWidth
      elRefSliderGroup.style.width = `${(childClientWidth + marginLeft) * children.length}px`
    }
  }

  const setSliderHeight = () => {
    sliderRef.current.style.height = sliderWrapperElemRef.current.clientHeight + "px"
  }

  useEffect(() => {
    // 存在children 为false的情况， 避免children不存在又创建BScroll实例
    if (instance.current === undefined) {
      if (Array.isArray(children) && children.length > 0) {
        if (mode === "banner" || mode === "normal-scroll-x") setSliderWidth()
      } else if (children && !Array.isArray(children)) {
        if (mode === "normal-scroll-y") {
          setSliderHeight()
        }
      }
      instance.current = { excuting: true }
      initial()
      return () => {
        console.log("children clean?")
      }
    }
  }, [children])

  useEffect(() => {
    return () => {
      sliderRef.current = null
      sliderGroupRef.current = null
      sliderWrapperElemRef.current = null
    }
  }, [])

  return (
    <div className="slider-wrapper" ref={sliderWrapperElemRef} style={{ height: (typeof height === "number" ? `${height}px` : height) || undefined }}>
      <div className="slider" ref={sliderRef}>
        <div className="slider-group" ref={sliderGroupRef}>
          {children}
        </div>
        {mode === "list-detail" && (
          <div className="pullup-tips">
            {beforePullUp && (
              <div className="before-trigger">
                <span className="pullup-txt">Pull up and load more</span>
              </div>
            )}
            {!beforePullUp && (
              <div className="after-trigger">
                <span className="pullup-txt">Loading...</span>
              </div>
            )}
          </div>
        )}
      </div>
      {mode === "banner" && dots.length > 0 && (
        <div className="dots">
          {dots.map((dot, index) => {
            let className = currentPageIndex === index ? "active" : ""
            className += " dots-item"
            return <div key={index} className={className}></div>
          })}
        </div>
      )}
    </div>
  )
}

const stateToProps = (state: any) => ({})

const dispatchToProps = (dispatch: any) => ({})

export default connect(stateToProps, dispatchToProps)(Slider)
