// vue/src/components/ProgressBar/ProgressBar.vue
<template>
  <div class="progress-bar-container" ref="progressBar" @click="progressClick">
    <div class="progress-bar"
      @mousedown.prevent="progressMouseStart"
      @mousemove.prevent="_progressMouseMove"
      @mouseup.stop="progressMouseEnd">
      <div class="progress-background"></div>
      <!-- 进度条 -->
      <div class="progress" ref="progress"></div>
      <!-- 当前进度按钮 -->
      <div class="progress-btn-wrapper" ref="progressBtn">
          <div class="progress-btn"></div>
      </div>
    </div>
  </div> 
</template>

<script>
import * as common from 'util/common'
// 进度条按钮宽度
const progressBarWidth = 16
// mousedown到mopuseup间隔时间, 用于区分click和mouseup, 超过150ms为mouse事件, 否则为click事件
const refelctTime = 0.1

export default {
  props: {
    precent: {
      type: Number,
      default: null
    }
  },
  data () {
    return {
      touch: {
        initiated: false,
        startX: 0
      },
      barWidth: null
    }
  },
  watch: {
    precent (newValue) {
      // timeupdate事件触发
      if (newValue > 0 && !this.touch.initiated && this.barWidth) {
        const offsetWidth = newValue * this.barWidth
        this.handleOffset(offsetWidth)
      }
    }
  },
  methods: {
    progressMouseStart (e) {
      this.touch.initiated = true
      this.touch.startX = e.pageX
      this.progressClientWidth = this.$refs.progress.clientWidth
      window.startTime = new Date().getTime()
    },
    // touchmove 和 mousemove 不一致
    progressMouseMove (e) {
      // ?   Math.max(0, this.progressClientWidth + deltaX) -->  0  移动超出左边界
      // ?   Math.max(0, this.progressClientWidth + deltaX) -->  delta  正常移动
      // ?
      // ?   this.barWidth 实际进度条宽度
      // ?   b = Math.max(0, this.progressClientWidth + deltaX)
      // ?   Math.min(a, b)  -->  a 超出右边界
      // ?   Math.min(a, b)  -->  b 正常移动
      if (!this.touch.initiated) return 
      const deltaX = e.pageX - this.touch.startX
      const offsetWidth = Math.min(this.barWidth, Math.max(0, this.progressClientWidth + deltaX))
      this.handleOffset(offsetWidth)
        .then(() => {
          this.$emit('progress-changing', this.getPrecent())
        })
    },
    // 节流目标函数
    _progressMouseMove (e) {
      common.throttle(this.progressMouseMove, 200, 0)(e)
    },
    progressMouseEnd () {
      // 出现问题: 从$refs获取样式数据会取到更新之前的数据
      // 在move事件上启用节流后, 可以避免使用定时器
      // 先抛出事件, 再将initiated修改为false
      this.$emit('progress-change', this.getPrecent())
      this.touch.initiated = false
    },
    progressClick (e) {
      // 解决mouseup和click重发触发的问题
      let diff = (new Date().getTime() - window.startTime) / 1000
      if (diff > refelctTime) return
      const rect = this.$refs.progressBar.getBoundingClientRect()
      const offsetWidth = e.pageX - rect.left
      this.handleOffset(offsetWidth)
        .then(() => {
          this.$emit('progress-change', this.getPrecent())
        })
    },
    handleOffset (offsetWidth) {
      return new Promise((resolve, reject) => {
        try {
          this.$refs.progress.style.width = `${offsetWidth}px`
          this.$refs.progressBtn.style.transform = `translate3d(${offsetWidth}px, 0, 0)`
        } catch (err) {
          reject(err)
        }
        // 保证获取更新后的dom
        this.$nextTick(() => resolve())
      })
    },
    getPrecent (clientWidth) {
      return this.$refs.progress.clientWidth / this.barWidth
      // return new Promise((resolve, reject) => {
      //   let barWidth = this.$refs.progressBar.clientWidth - progressBarWidth
      //   resolve(this.$refs.progress.clientWidth / barWidth)
      //   // this.$nextTick(() => {
      //     // let width = this.$refs.progress.clientWidth
      //     // width = parseFloat(width.substring(0, width.length - 2))
      //     // resolve(width / barWidth)
      //   //})
      // })
    }
  },
  created () {},
  mounted () {
    this.barWidth = this.$refs.progressBar.clientWidth - progressBarWidth
  }
}
</script>

<style lang="less">
  .progress-bar-container {
    display: block;
    width: 100%;// 14px是block-current直径
    height: 50px;
    .progress-bar {
      position: relative;
      width: calc(~"100% - 16px");
      height: 100%;
      .progress-background, .progress {
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
        height: 5px;
        // background-color: rgba(255, 255, 255, 0.2);
      }
      .progress-background {
        z-index: 0;
        width: 100%;
        background-color: rgba(255, 255, 255, 0.2);
      }
      .progress {
        transition: all .17s linear;
        z-index: 10;
        background-color: rgb(184, 37, 37);
      }
      .progress-btn-wrapper {
        position: absolute;
        top: 16px;
        transition: all .2s linear;
        z-index: 10;
        width: 30px;
        height: 30px;
        .progress-btn {
          position: relative;
          top: 0;
          width: 16px;
          height: 16px;
          border-radius: 50%;
          background-color: #fff;
        }
      }
    }
  } 
</style>

// react-mobile/src/components/ProgressBar/index.tsx
import { useContext, useEffect, useRef, useState } from "react";

import { AppContext } from "@/store";
import { throttle } from "@/utils/tools";
// import {useWatch} from '@/utils/hook'
import "./index.less";

// 进度条按钮宽度
const progressBarWidth = 16;
// mousedown到mopuseup间隔时间, 用于区分click和mouseup, 超过150ms为mouse事件, 否则为click事件
const refelctTime = 0.1;

// ! 问题: 全面屏手势滑动会进行翻页, 导致touchmove不能正确调用
// ? 测试发现小米手机浏览器存在原生滑动事件, 导致问题, 在微信中可正常使用

const ProgressBar = (props: any) => {
  const { percent, progressWidth } = props;
  const progressBar = useRef<any>(null),
    progress = useRef<any>(null),
    progressBtn = useRef<any>(null);
  const { startTime, dispatch, EventEmitter } = useContext<any>(AppContext);
  const [touch, setTouch] = useState({
    initiated: false,
    startX: 0,
  });
  const [progressClientWidth, setProgressClientWidth] = useState<number>(0);
  const [barWidth, setBarWidth] = useState<number | null>(null);

  const progressClick = (e: any) => {
    // 解决mouseup和click重发触发的问题
    let diff = (new Date().getTime() - startTime) / 1000;
    if (diff > refelctTime) return;
    // .getBoundingClientRect()
    const rect = progressBar.current.getBoundingClientRect();
    const offsetWidth = e.touches[0].clientX - rect.left;
    handleOffset(offsetWidth);
    EventEmitter.emit("progress-change", getPrecent());
  };

  // const handleOffset = (offsetWidth: any) => {
  //   return new Promise((resolve, reject) => {
  //     try {
  //       progress.current.style.width = `${offsetWidth}px`;
  //       progressBtn.current.style.transform = `translate3d(${offsetWidth}px, 0, 0)`;
  //       resolve(true)
  //     } catch (err) {
  //       reject(err);
  //     }
  //     // 保证获取更新后的dom
  //     // this.$nextTick(() => resolve())
  //   });
  // };

  const handleOffset = (offsetWidth: any) => {
    progress.current.style.width = `${offsetWidth}px`;
    progressBtn.current.style.transform = `translate3d(${offsetWidth}px, 0, 0)`;
  };

  const progressTouchMove = (e: any) => {
    // ?   Math.max(0, this.progressClientWidth + deltaX) -->  0  移动超出左边界
    // ?   Math.max(0, this.progressClientWidth + deltaX) -->  delta  正常移动
    // ?
    // ?   this.barWidth 实际进度条宽度
    // ?   b = Math.max(0, this.progressClientWidth + deltaX)
    // ?   Math.min(a, b)  -->  a 超出右边界
    // ?   Math.min(a, b)  -->  b 正常移动

    if (!touch.initiated) return;
    const deltaX = e.touches[0].clientX - touch.startX;
    const offsetWidth = Math.min(
      barWidth === null ? 0 : barWidth,
      Math.max(0, progressClientWidth + deltaX)
    );
    handleOffset(offsetWidth);
    // debugger
    EventEmitter.emit("progress-changing", getPrecent());
  };

  const progressTouchStart = (e: any) => {
    setTouch({
      initiated: true,
      startX: e.touches[0].clientX,
    });
    setProgressClientWidth(progress.current.clientWidth);
    dispatch({ type: "startTime", value: new Date().getTime() });
  };

  const _progressTouchMove = (e: any) => {
    throttle(progressTouchMove, 200, 0)([e]);
    // progressTouchMove(e)
  };

  const progressTouchEnd = () => {
    // 出现问题: 从$refs获取样式数据会取到更新之前的数据
    // 在move事件上启用节流后, 可以避免使用定时器
    // 先抛出事件, 再将initiated修改为false
    EventEmitter.emit("progress-change", getPrecent());
    setTouch({
      ...touch,
      initiated: false,
    });
  };

  const getPrecent = () => {
    let num = progress.current.clientWidth / (barWidth === null ? 0 : barWidth)
    return num.toFixed(4);
  };

  useEffect(() => {
    setTimeout(() => {
      setBarWidth(progressBar.current.clientWidth - progressBarWidth);
    }, 100)
  }, []);

  // useWatch(percent, (old) => {
  //   // timeupdate事件触发
  //   if (percent > 0 && !touch.initiated && barWidth) {
  //     const offsetWidth = percent * barWidth
  //     handleOffset(offsetWidth)
  //   }
  // })

  useEffect(() => {
    // timeupdate事件触发
    if (percent > 0 && !touch.initiated && barWidth !== null) {
      const offsetWidth = percent * barWidth
      handleOffset(offsetWidth);
    }
  }, [percent]);

  return (
    <div
      className="progress-bar__container"
      ref={progressBar}
      onClick={progressClick}
      style={{width: `${progressWidth}px`}}
    >
      <div
        className="progress-bar"
        onTouchStart={progressTouchStart}
        onTouchMove={_progressTouchMove}
        onTouchEnd={progressTouchEnd}
      >
        <div className="progress-bar__background"></div>
        {/* 进度条 */}
        <div className="progress-bar--progress" ref={progress}></div>
        {/* 当前进度按钮 */}
        <div className="progress-bar--btn__wrapper" ref={progressBtn}>
          <div className="progress-bar--btn"></div>
        </div>
      </div>
    </div>
  );
};

export default ProgressBar;
